services:
  php:
    image: php:7-fpm          # Official PHP 7.x FPM image (defaults to latest 7.x release)
    container_name: php
    volumes:
      - ./src:/var/www/html
    networks:
      - appnet

  mysql:
    image: mysql:5.7
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypass
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - appnet

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - appnet

volumes:
  db_data:

networks:
  appnet: